[package]
name = "termdraw"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]
chrono = { version = "0.4.20" }
chrono-tz = "0.6.3"
hostname = "0.3.1"
libc = "0.2.102"
rand = "0.8.4"
termios = "0.3.3"
